[build]
  command = "python app.py"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

[dev]
  functions = "netlify/functions"

[build.packages]
  - mysql-client
  - libmysqlclient-dev
