[build]
  command = "python app.py"
  functions = "netlify/functions/"
  publish = "./"

[context.production.environment]
  FLASK_ENV = "production"
  MYSQL_HOST = "127.0.0.1"
  MYSQL_USER = "root"
  MYSQL_PASSWORD = "Monalisa@2001#"
  MYSQL_DB = "user_login_info"

[context.deploy-preview.environment]
  FLASK_ENV = "development"
  MYSQL_HOST = "127.0.0.1"
  MYSQL_USER = "root"
  MYSQL_PASSWORD = "Monalisa@2001#"
  MYSQL_DB = "user_login_info"

[context.branch-deploy.environment]
  FLASK_ENV = "development"
  MYSQL_HOST = "127.0.0.1"
  MYSQL_USER = "root"
  MYSQL_PASSWORD = "Monalisa@2001#"
  MYSQL_DB = "user_login_info"
